---
- include: Debian.yml
  when: ansible_os_family == 'Debian'
- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
- name: make uhubctl
  become: no
  make:
  args:
    chdir: /usr/local/src/uhubctl
- name: install uhubctl
  become: yes
  make:
    target: install
  args:
    chdir: /usr/local/src/uhubctl