---
- name: install uhubctl dependencies
  become: yes
  apt:
    state: present
    name: [
      'libusb-1.0-0-dev',
      'libusb-1.0-0',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed