---
# tasks file for install_uhubctl
- name: clone uhubctl
  git:
    repo: https://github.com/mvp/uhubctl.git
    dest: /usr/local/src/uhubctl
    clone: yes
    update: yes
    version: "{{ uhubctl_version }}"
  register: uhubctl_repo
  retries: 3
  delay: 10
  until: not uhubctl_repo.failed
- name: set ansible user as owner of uhubctl folder
  file:
    path: /usr/local/src/uhubctl
    owner: "{{ ansible_user }}"
    recurse: true
- name: check uhubctl exists
  stat:
    path: /usr/sbin/uhubctl
  register: uhubctl_check
- include: compile_uhubctl.yml
  when: not uhubctl.stat.exists or uhubctl_repo.before != uhubctl_repo.after