---
- name: install uhubctl dependencies
  become: yes
  yum:
    state: present
    name: [
      'libusb',
      'libusb-devel',
    ]
  register: result
  retries: 3
  delay: 10
  until: not result.failed